name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  ci:
    name: CI
    # Skip tags. This 1-liner is equivalent to ~10LOC to do the same in `on`.
    if: github.event.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm clean-install --ignore-scripts
      - name: Build Project
        run: npx nr build
      - name: Run Tests
        run: |
          npx nr test.coverage
          bash <(curl -s https://codecov.io/bash)
